# Generated by Django 4.1.1 on 2022-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UneApplication", "0002_alter_modelproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelproduct",
            name="show",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
