# Generated by Django 4.0.6 on 2022-07-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(default=None, null=True)),
                ('brand', models.CharField(default=None, max_length=255, null=True)),
                ('photo_url', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=int, verbose_name='Количество')),
                ('chat_id', models.PositiveIntegerField(blank=True, default=int, null=True, verbose_name='Чат ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cigarettes.modelproduct', verbose_name='ID в каталоге')),
            ],
        ),
    ]
