# Generated by Django 4.0.6 on 2022-07-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcart',
            name='product',
            field=models.ForeignKey(blank=True, default=dict, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cigarettes.modelproduct', verbose_name='ID в каталоге'),
        ),
    ]
