# Generated by Django 4.0.6 on 2022-07-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0003_remove_modelcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Cigarettes.modelproduct', verbose_name='ID в каталоге'),
        ),
    ]
