# Generated by Django 4.0.6 on 2022-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0004_modelcart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcart',
            name='product',
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
