# Generated by Django 4.0.6 on 2022-07-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0006_modelcart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcart',
            old_name='product',
            new_name='product_id',
        ),
    ]
