# Generated by Django 4.0.6 on 2022-07-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0008_rename_product_id_modelcart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
