# Generated by Django 4.1 on 2022-09-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0010_modelcategory_alter_modelcart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcategory',
            name='category_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cigarettes.modelcategory'),
        ),
    ]
