# Generated by Django 4.1 on 2022-09-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0011_alter_modelcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcategory',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='volume',
            field=models.ImageField(blank=True, default=1, upload_to='', verbose_name='Кол-во затяжек'),
        ),
        migrations.AlterField(
            model_name='modelcategory',
            name='category_name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cigarettes.modelcategory', verbose_name='Категория'),
        ),
    ]
