# Generated by Django 4.1 on 2022-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0012_alter_modelcategory_options_modelproduct_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='volume',
            field=models.IntegerField(blank=True, default=1, verbose_name='Кол-во затяжек'),
        ),
    ]
