# Generated by Django 4.1 on 2022-09-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0014_alter_modelproduct_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='volume',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Кол-во'),
        ),
    ]
