# Generated by Django 4.1 on 2022-09-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0015_alter_modelproduct_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='Cigarettes.modelcategory', verbose_name='Категория'),
        ),
    ]
