# Generated by Django 4.1 on 2022-09-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0016_alter_modelproduct_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
