# Generated by Django 4.1 on 2022-09-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cigarettes', '0019_brandcategory_alter_modelproduct_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandCategory',
            new_name='ModelBrand',
        ),
    ]
